server_configurations:

  # Database APIs
  authentication_url: https://auth-test-app.tags.lk/oauth/token
  username: ivca
  password: iVCA@7455
  client_id: xUreERewqD
  load_visitor_url: https://visitor-test-app.tags.lk/api/v1/ivca/visitors/sync
  load_cam_url: https://visitor-test-app.tags.lk/api/v1/ivca/cameras/sync
  post_visitor_url: https://visitor-test-app.tags.lk/api/v1/ivca/visitor/identify
  cam_offline_url: https://visitor-test-app.tags.lk/api/v1/ivca/camera/{}/offline


# Don't Change the following parameters unless you know what it means

hyper_params:

  # hyper parameters for controlling feature tracker
  feature_tracker:
    min_frames_appeared_to_validate : 5
    max_frames_disappeared_to_discard : 30
    validation_window_size: 5
    matching_cos_threshold: 0.9

  # hyper parameters corresponding to face recognition model
  fr_model:
    path: model/arc_res50.pth
    threshold: 0.55
    guess_threshold: 0.45

  # hyper parameters to tune face detection model
  fd_model:
    path: model/
    min_detection_size: 60

  # hyper parameters to manage local records
  local_record:
    stack_size: 15
    rerecord_ignore_time_seconds: 60

  # additional daily buffer room for adding new users
  user_record_buffer: 100

  # Number of retries to be made before cam goes offline
  retries: 5
  retry_duration: 5 

debug_params:
  # bool value to print to terminal run time of each step
  run_time_print: False
  # bool value to print API access response status
  api_access_print: True
  # Running server
  host: 0.0.0.0
  port: 9090 
